#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/66b60b66-cd95-400e-9648-d0155f96a7fd

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "DHT.h"
#define DHT_PIN 32
#define DHTTYPE DHT22

#include "thingProperties.h"

DHT dht(DHT_PIN, DHTTYPE);
float dhtTemperature;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  Serial.println("START reading DHT ===============");
  delay(1500);
  dht.begin();
}


void readEnvTemperature() {
  dhtTemperature = dht.readTemperature();
  temperature = dhtTemperature;
  Serial.print("Temp: ");
  Serial.print(dhtTemperature);
  Serial.println("C");
}

void loop() {
  ArduinoCloud.update();
  // Your code here

  readEnvTemperature();
  Serial.println("=============");
  delay(2000);
}







