// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

void onTriggerLevelChange();

float currentHumid;
float currentTemp;
int currentMoist;
int triggerLevel;
bool pumpStatus;

void initProperties(){

  ArduinoCloud.addProperty(currentHumid, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(currentTemp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(currentMoist, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(triggerLevel, READWRITE, ON_CHANGE, onTriggerLevelChange);
  ArduinoCloud.addProperty(pumpStatus, READ, ON_CHANGE, NULL);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

#error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
